Fix exit when token is missing
'exit' is an Event object, better use sys.exit() instead, to avoid this
issue:

  TypeError: 'Event' object is not callable